PhotoGallery/Models/Image.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PhotoGallery.Models
{
    public class Image
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(255)]
        public string Title { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }
        public virtual ApplicationUser Author { get; set; }

        [ForeignKey("Gallery")]
        public int GalleryId { get; set; }
        public virtual Gallery Gallery { get; set; }

        public string Path { get; set; }

        public int Vote { get; set; }
    }
}

PhotoGallery/Models/ImageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoGallery.Models
{
    public class ImageViewModel
    {
        public int? Id { get; set; }
        public string Title { get; set; }
        public int GalleryId { get; set; }
        public ICollection<Image> Images { get; set; }
        public ICollection<Gallery> Galleries { get; set; }
        public HttpPostedFileBase Photo { get; set; }
        public Image Image { get; set; }
        public Gallery Gallery { get; set; }
    }
}

PhotoGallery/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PhotoGallery.Models;

namespace PhotoGallery.Controllers
{
    public class ImageController : Controller
    {
        //GET: Image/List
        public ActionResult List()
        {
            using (var db = new ApplicationDbContext())
            {
                var model = new ImageViewModel();
                var images = db.Images
                    .Include(a => a.Author)
                    .ToList();

                model.Images = images;
                return View(model);
            }
        }

        //Get images by gallery
        public ActionResult ListGalleryImgages(int?id)
         {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (var db = new ApplicationDbContext())
            {
                var model = new ImageViewModel();
                var galleryImages = db.Images
                    .Where(g => g.GalleryId == id)
                    .Include(i=>i.Author)
                    .ToList();
                var currentGalery = db.Galleries.First(g => g.Id == id);
                model.Gallery = currentGalery;
                model.Images = galleryImages;
                
                return View(model);
            }
        }

        //GET: Image/Details
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var db = new ApplicationDbContext())
            {
                var model = new ImageViewModel();
                var image = db.Images.First(i => i.Id == id);
                model.Image = image;

                return View(model);
            }
        }

        //GET: Image/Upload
        [Authorize]
        public ActionResult Upload()
        {
            using (var db = new ApplicationDbContext())
            {
                var model = new ImageViewModel();
                var galleries = db.Galleries
                    .OrderBy(g => g.Name)
                    .ToList();
                model.Galleries = galleries;
                return View(model);
            }
        }

        //POST: Image/Upload
        [HttpPost]
        [Authorize]
        public ActionResult Upload(ImageViewModel model, HttpPostedFileBase photo, HttpPostedFileBase avatar)
        {
            using (var db = new ApplicationDbContext())
            {
                model.Galleries = GetAllGalleries(db);

                var fileForUpload = photo ?? avatar;
                if (fileForUpload != null && fileForUpload.ContentLength > 0)
                {
                    if (!IsFileValid(fileForUpload.ContentType))
                    {
                        ViewBag.Message = "Only JPEG, JPG, PNG or GIF files are allowed!";
                        return View(model);
                    }
                    else if (!IsFileSizeValid(fileForUpload.ContentLength))
                    {
                        ViewBag.Message = "The file size must be up to 1MB!";
                        return View(model);
                    }

                    try
                    {
                        var image = new Image();

                        var fileName = Path.GetFileName(fileForUpload.FileName);
                        fileName = fileName.Replace(" ", "_");

                        //Upload photo to galleries
                        if (photo != null)
                        {
                            var path = Path.Combine(Server.MapPath("~/Images"), fileName);
                            fileForUpload.SaveAs(path);

                            var authorId = GetAuthorId(db);

                            image.AuthorId = authorId;
                            image.Title = model.Title;
                            image.GalleryId = model.GalleryId;
                            image.Path = fileName;

                            db.Images.Add(image);
                            db.SaveChanges();
                        }

                        //Upload avatar image
                        else if (avatar != null)
                        {
                            var path = Path.Combine(Server.MapPath("~/Images/Avatar"), fileName);
                            fileForUpload.SaveAs(path);

                            var currentUserId = User.Identity.GetUserId();
                            var user = db.Users
                                .First(u => u.Id == currentUserId);
                            user.Avatar = fileName;
                            db.Entry(user).State = EntityState.Modified;
                            db.SaveChanges();

                            ViewBag.Message = "File uploaded successfully";

                            return RedirectToAction("Details", "User");
                        }
                        ViewBag.Message = "File uploaded successfully";

                        return View(model);

                    }
                    catch (Exception ex)
                    {

                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                        return View(model);
                    }
                }
                else
                {
                    ViewBag.Message = "You have not specified a file.";
                    return View(model);
                }
            }
        }

        //Get votes
        public ActionResult Vote(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var db = new ApplicationDbContext())
                {
                    var model = new ImageViewModel();
                    var image = db.Images.First(i => i.Id == id);

                    var imgVotes = db.Images.First(i => i.Id == id).Vote;
                    imgVotes++;
                    image.Vote = imgVotes;

                    model.Image = image;
                    
                    db.Entry(image).State = EntityState.Modified;
                    db.SaveChanges();

                    return View(model);
                }
        }

        private ICollection<Gallery> GetAllGalleries(ApplicationDbContext db)
        {
            var galleries = db.Galleries
                .OrderBy(g => g.Name)
                .ToList();
            return galleries;
        }

        private string GetAuthorId(ApplicationDbContext db)
        {
            var authorId = db.Users
                .Where(a => a.UserName == this.User.Identity.Name)
                .First()
                .Id;
            return authorId;
        }

        private bool IsFileValid(string contentType)
        {
            return contentType.Equals("image/jpeg") || contentType.Equals("image/jpg") ||
                   contentType.Equals("image/png") || contentType.Equals("image/gif");
        }

        private bool IsFileSizeValid(int fileSize)
        {
            return ((fileSize / 1024) / 1024) < 1;
        }
    }
}

PhotoGallery/Views/Image/Details.cshtml
@model PhotoGallery.Models.ImageViewModel
@{
    ViewBag.Title = null;
}
<h2>Image details</h2>
@using (Html.BeginForm("Details", "Image", null))
{
    <div>
        <div class="row-new alpha60">
                <div align="center">
                    <img class="img-responsive" src="~/Images/@Model.Image.Path" style="max-width: 680px" />
                    <hr />
                    <div class="row">
                        <div class="infoline" style="padding: 3%; margin:15px; background-color: cornsilk">
                            <div class="col-sm-1">
                                <a href="@Url.Action("Vote", "Image", new {@id = Model.Image.Id})" class="btn btn-warning btn-xs">Vote!</a>
                            </div>
                            <div class="col-sm-1">
                                <p>
                                    <b>Votes:@Model.Image.Vote</b>
                                </p>
                            </div>
                            <div class="col-lg-6" align="left">
                                <p>
                                    <b>Title:</b><i>"@Model.Image.Title"</i>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
        </div>
    </div>
}

PhotoGallery/Views/Image/List.cshtml
@model PhotoGallery.Models.ImageViewModel
@{
    ViewBag.Title = null;
}

<div class="container">
    <div class="row-new">
        <div class="col-lg-12">
            <h1 class="page-header">Recent photo`s</h1>
        </div>
        @foreach (var image in Model.Images)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="padding-bottom: 10px" >
                <div class="thumbnail" align="center">
                    <a href="@Url.Action("Details","Image", new {id=image.Id})">
                        <img class="img-responsive" src="~/Images/@image.Path" alt="image" style="max-height: 172px" />
                    </a>
                    <div class="caption" align="left">
                        <p>
                            <b>Title:</b> 
                            <i> @image.Title</i>
                        </p>
                        <div class="pull-right">
                            <p>
                                <b>
                                    Votes:@image.Vote
                                </b>
                            </p>
                        </div>
                        <div>
                            <p>
                                <b>
                                    Author:
                                </b>  
                                <a href="@Url.Action("Details", "User", new {id = image.Author.Id})">@image.Author.UserName</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

PhotoGallery/Views/Image/ListGalleryImgages.cshtml
@model PhotoGallery.Models.ImageViewModel
@{
    ViewBag.Title = "ListGalleryImgages";
}

<h2>@Model.Gallery.Name Gallery</h2>
<hr/>
<div class="container">
    <div class="row">
        <div class="col-lg-12">
        </div>
        @foreach (var image in Model.Images)
        {
            <div class="col-lg-3 col-md-4 col-xs-6 thumb" style="padding-bottom: 10px">
                <div class="thumbnail" align="center">
                    <a href="@Url.Action("Details","Image", new {id=image.Id})">
                        <img class="img-responsive" src="~/Images/@image.Path" alt="image" style="max-height: 172px" />
                    </a>
                    <div class="caption" align="left">
                        <p><b>Title:</b><i>@image.Title</i></p>
                        <div class="pull-right">
                            <p><b>Votes:@image.Vote</b></p>
                        </div>
                        <div>
                            <p>Author: <a href="@Url.Action("Details", "User",new {id=image.Author.Id})">@image.Author.UserName</a></p>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

PhotoGallery/Views/Image/Upload.cshtml
@model PhotoGallery.Models.ImageViewModel

@{
    ViewBag.Title = "Upload";
}

<h2>Upload photo</h2>

@using (Html.BeginForm("Upload","Image", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.GalleryId, new {@class = "control-label col-md-2"})
            <div class="dropdown col-sm-10">
                @Html.DropDownListFor(m => m.GalleryId,
                    new SelectList(Model.Galleries, "Id", "Name"),
                    new {@class = "btn btn-info col-sm-12"})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <label for="photo">Upload Image:</label>
                <input type="file" name="photo" id="photo" />
                <hr/>
                <input type="submit" value="Upload Image" class="btn btn-default" />
                <br><br>
                @ViewBag.Message
            </div>
        </div>
    </div>
}

PhotoGallery/Views/Image/Vote.cshtml
@model PhotoGallery.Models.ImageViewModel
@{
    ViewBag.Title = "Vote";
}
<div style="">
    <div class="row-new alpha60">
        <div class="row-new">

            <h2>Thank you for your vote!</h2>
            <div class="btn-group-vertical">
                <a href="@Url.Action("Details","Image", new {@id=Model.Image.Id})" class="btn btn-default">Head back to the photo!</a>
                <a href="@Url.Action("Details", "User")" class="btn btn-default">Back to user images</a>
            </div>
        </div>
    </div>
</div>