PhotoGallery/Models/UsersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoGallery.Models
{
    public class UsersViewModel
    {
        public IList<ApplicationUser> Users { get; set; }

        public IList<Image> Images { get; set; }

        public HttpPostedFileBase Avatar { get; set; }

        public IList<Image> ImagesByUser(ApplicationUser user)
        {
            using (var db = new ApplicationDbContext())
            {
                var images = db.Images.Where(a => a.Author.UserName == user.UserName).ToList();

                return images;
            }
        }

    }
}

PhotoGallery/Controllers/Admin/GalleryController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using PhotoGallery.Models;

namespace PhotoGallery.Controllers.Admin
{
    public class GalleryController : Controller
    {
        // GET: Gallery
        public ActionResult List()
        {
            using (var db = new ApplicationDbContext())
            {
                var galleries  = db.Galleries
                    .Include(g=>g.Images)
                    .OrderBy(g => g.Name)
                    .ToList();
                
                return View(galleries);
            }
        }

        [Authorize(Roles = "Admin")]
        //GET: Gallery/Create
        public ActionResult Create()
        {
            return View();
        }

        //POST: Gallery/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult CreateAction(Gallery gallery)
        {
            if (ModelState.IsValid)
            {
                using (var db = new ApplicationDbContext())
                {
                    db.Galleries.Add(gallery);
                    db.SaveChanges();
                }
            }

            return RedirectToAction("List");
        }

        //Render the gallery drop down menu
        public PartialViewResult GalleriesMenu()
        {
            using (var db = new ApplicationDbContext())
            {
                var model = new ImageViewModel();
                var galleries = db.Galleries
                    .Include(g => g.Images)
                    .OrderBy(g => g.Name)
                    .ToList();
                model.Galleries = galleries;

                return PartialView(model);
            }
        }


    }

}

PhotoGallery/Controllers/Admin/UsersController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using PhotoGallery.Models;

namespace PhotoGallery.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        //Get: Index
        public ActionResult AdminPage()
        {
            return View();
        }

        //Get: Users/List
        public ActionResult List(ApplicationUser user)
        {
            using (var db = new ApplicationDbContext())
            {
                var model = new UsersViewModel();
                var users = db.Users
                    .ToList();
                model.Users = users;
                return View(model);
            }
        }

        private bool IsAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var userManager  = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

                var userRole = userManager.GetRoles(user.GetUserId());

                if (userRole[0] == "Admin")
                {
                    return true;
                }
                return false;
            }
            return false;
        }


    }
}

PhotoGallery/Controllers/UserController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PhotoGallery.Models;

namespace PhotoGallery.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Details(string id)
        {
            var model = new UserDetailsViewModel();
            model.Images = GetImagesByUser(id);

            using (var db = new ApplicationDbContext())
            {
                var user = db.Users.First(u => u.Id == id);
                model.User = user;
            }

            return View(model);
        }

        //Get images by user
        public IList<Image> GetImagesByUser(string id)
        {
            using (var db = new ApplicationDbContext())
            {
                var images = db.Images
                    .Where(a => a.AuthorId == id)
                    .Include(i => i.Author)
                    .ToList();

                return images;
            }
        }

    }
}

PhotoGallery/Views/Users/AdminPage.cshtml
@{
    ViewBag.Title = "Admin Page";
}
<div style="">
    <div class="row-new alpha60">
        <div class="row-new">
            <h3>@ViewBag.Title</h3>
            <div class="btn-group btn-group-sm">
                @Html.ActionLink("Users", "List", "Users", new {@class = "btn btn-warning"})
                @Html.ActionLink("Galeries", "List", "Gallery", new {@class = "btn btn-warning"})
            </div>
        </div>
    </div>
</div>

PhotoGallery/Views/Users/List.cshtml
@model PhotoGallery.Models.UsersViewModel
@{
    ViewBag.Title = "Users list";
}
<div style="">
    <div class="row-new alpha60">
        <div class="row-new">
            <h2>@ViewBag.Title</h2>
            <div>
                <table class="table table-striped table-hover ">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Username</th>
                            <th>Images count</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Users.Count; i++)
                        {
                            <tr>
                                <td>@(i + 1)</td>
                                <td>@Model.Users[i].UserName</td>
                                <td>@Model.ImagesByUser(Model.Users[i]).Count</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>